name: Deploy / Atualizar Servidores
run-name: Deploy do artefato ${{ inputs.releasetag }} em ${{ inputs.ambiente }} disparada por ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: "Nome do artefato/versÃ£o"
        type: string
        required: true
      ambiente:
        type: choice
        description: 'Ambiente'
        required: true
        default: 'TST'
        options:
        - TST
        - PRD

jobs:
  app_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: '${{ github.repository }}'
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'backend.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download Frontend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: '${{ github.repository }}'
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'frontend.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Descompactar arquivos
        shell: bash
        run: |
          mkdir backend
          mkdir frontend
          unzip backend.zip -d backend
          unzip frontend.zip -d frontend
      
      - name: Configurar SSH Key
        run: |
          echo "${{ secrets.KEYPAR_RSA }}" > keypair.pem
          sudo chmod 400 keypair.pem
          mkdir -p ~/.ssh/
          ssh-keyscan -H $(echo ${{ secrets.URL_TST }} | sed 's/.*@//') >> ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
      
      - name: Atualizar em TST
        if: ${{ inputs.ambiente == 'TST' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz backend/* ${{ secrets.URL_TST }}:${{ secrets.PASTA_PROJETO }}/tst/backend
          rsync -e "ssh -i keypair.pem" -avz frontend/* ${{ secrets.URL_TST }}:${{ secrets.PASTA_PROJETO }}/tst/frontend
      
      - name: Atualizar em PRD
        if: ${{ inputs.ambiente == 'PRD' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz backend/* ${{ secrets.URL_PRD }}:${{ secrets.PASTA_PROJETO }}/prd/backend
          rsync -e "ssh -i keypair.pem" -avz frontend/* ${{ secrets.URL_PRD }}:${{ secrets.PASTA_PROJETO }}/prd/frontend
